apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: <access_key_id>
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: <secret_access_key>
  RCLONE_CONFIG_S3_ENDPOINT: http://<minio-endpoint>:9000
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
